In [1]:
%load_ext autoreload
%autoreload 2

import os

os.chdir("../../")

## Note 

- To run this notebook, run this first: `python -m src.data.restructure_entrainment_coding_data`
- It is recommended to run `python -m src.data.restructure_entrainment_coding_data --output_csv` for real analysis

In [2]:
import pandas as pd

dogs_df = pd.read_excel("baskets_dogs_data/dogs.xlsx")
baskets_df = pd.read_excel("baskets_dogs_data/baskets.xlsx")

In [6]:
dogs_df.head(1)

,Round,Order,TargetObjectIndex,Pair_20,Pair_21,Pair_22,Pair_23,Pair_24,Pair_34,Pair_35,Pair_37,Pair_43,Pair_45
0,1,Dog 1,2,"D: Mike, do you know anything about dogs?\n \n...","D: Okie dokie\nUm, number one is a dog\nIt's ...","D: Ok, number one--it's uh--it's a dog with t...","D: Ok (laughs)\nOk, this dog is standing upri...","D: Okay\nUm, dog number one is uh--(laughs)\n...",D: In the middle of the dog is black\nIt's fa...,D: Picture number one\n\nM: Mm-hmm\n\nD: Is...,D: Uh…the first dog's uh...t-t-t-t (clicks to...,"M: Ok, and what color is it?\n\nD: It has blac...","D: Ok, Joanne…the first dog…um it's standing ..."

In [7]:
dogs_df.columns

Index(['Round', 'Order', 'TargetObjectIndex', 'Pair_20', 'Pair_21', 'Pair_22',
       'Pair_23', 'Pair_24', 'Pair_34', 'Pair_35', 'Pair_37', 'Pair_43',
       'Pair_45'],
      dtype='object')

In [16]:
def get_pair_transcript_and_entrainment_coding_data(
        object_category: str, 
        pair_col: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    
    if object_category == "dogs":
        df = dogs_df
    elif object_category == "baskets":
        df = baskets_df
    else:
        raise ValueError("object_category must be either 'dogs' or 'baskets'")

    assert pair_col in df.columns, f"{pair_col} not found in dataframe columns"

    pair_ix = pair_col.split("_")[-1]
    transcript_df = df[['Round', 'Order', 'TargetObjectIndex', pair_col]]
    entrainment_coding_df = pd.read_json("baskets_dogs_data/restructured_entrainment_coding_data/"
                                         f"{object_category}/pair{pair_ix}.json")
    
    return transcript_df, entrainment_coding_df

## Check one example

Hypothesis:

- Card1 to Card10 correspond to the card orders in the first 1
- The descriptions from `entrainment_coding_df` are extracted from `transcript_df` (extractive summarization)

In [32]:
from src.data.utils import pretty_print

pair_col = "Pair_23"
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="dogs", pair_col=pair_col
)
transcript_df.shape, entrainment_coding_df.shape

((40, 4), (4, 10))

In [19]:
pretty_print(entrainment_coding_df.T)

In [22]:
TargetObjectIndices = transcript_df[transcript_df['Round'] == 1].TargetObjectIndex
TargetObjectIndices

0     2
1     8
2     4
3    10
4     6
5     3
6     7
7     1
8     9
9     5
Name: TargetObjectIndex, dtype: int64

In [ ]:
pretty_print(transcript_df[transcript_df.TargetObjectIndex == TargetObjectIndices[0]])

In [ ]:
from tqdm import tqdm
from src.llms.openai import get_response

prompt_tmp = """
You will be given a text description and a excerpt from a conversation transcript. \
Your task is to verify if the description is extracted from the transcript. \
Compare the description and the transcript excerpt carefully. And output "YES" if \
all points in the description are found in the transcript excerpt, otherwise output "NO". \
Do not provide any additional explanation.

### Description

{description}

### Transcript 

{transcript}

### Answer
""".strip()

out = []
progress_bar = tqdm(total=2 * 10 * 10 * 4, position=0, 
                    leave=True, desc="Processing Pairs")

for category in ["dogs", "baskets"]:

    for pair_col in dogs_df.columns.to_list()[3:]:
        transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
            object_category=category, pair_col=pair_col
        )

        TargetObjectIndices = transcript_df[transcript_df['Round'] == 1].TargetObjectIndex

        for ix, target_obj_index in enumerate(TargetObjectIndices):
            transcripts = transcript_df[transcript_df.TargetObjectIndex 
                                        == target_obj_index][pair_col]
            descriptions = entrainment_coding_df[f"Card{ix+1}"]

            assert len(transcripts) == len(descriptions), \
                "Mismatch in number of rounds between transcript and entrainment coding data"

            for j, (transcript, description) in enumerate(zip(transcripts, descriptions)):
                description = " ".join(description)
                prompt = prompt_tmp.format(
                    description=description,
                    transcript=transcript
                )
                _, response = get_response(
                    prompt,
                    model_name="gpt-4o-mini",
                )
                out.append(
                    {
                        "Object Category": category,
                        "Participant Pair": pair_col,
                        "Round": j + 1,
                        "TargetObjectIndex": target_obj_index,
                        "Model Response": response,
                    }
                )
                progress_bar.update(1)

Processing Pairs:   1%|▏         | 1/80 [00:16<21:11, 16.09s/it]

Processing Pairs: 800it [29:55,  2.21s/it]

In [50]:
out_df = pd.DataFrame(out)
out_df["Model Response"].value_counts()

Model Response
YES    790
NO      10
Name: count, dtype: int64

In [59]:
out_df["Model Response"].to_csv("notebooks/outputs/entrainment_coding_verification_responses.csv", index=False)

## Manual Inspection

In [60]:
out_df[out_df["Model Response"] == "NO"]

    Object Category Participant Pair  Round  TargetObjectIndex Model Response
16             dogs          Pair_20      1                  6             NO
33             dogs          Pair_20      2                  9             NO
65             dogs          Pair_21      2                  7             NO
73             dogs          Pair_21      2                  9             NO
144            dogs          Pair_23      1                  7             NO
414         baskets          Pair_20      3                  5             NO
417         baskets          Pair_20      2                 10             NO
440         baskets          Pair_21      1                  9             NO
530         baskets          Pair_23      3                  7             NO
752         baskets          Pair_43      1                  2             NO

### Dogs

In [61]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="dogs", pair_col="Pair_20"
)
pretty_print(transcript_df[transcript_df.TargetObjectIndex == 6])

In [ ]:
# Round 1 needs double check, but round 2 looks correct.
pretty_print(entrainment_coding_df[["Card5"]].loc[["Round1", "Round2"]])

In [68]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="dogs", pair_col="Pair_21"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex.isin([7, 9])) & 
                           (transcript_df.Round.isin([1, 2]))])

In [ ]:
# Card7, Round 2: double check
# Card9, Round 2: double check
# possible: the segmentation of the transcript into 10 parts has some issues
pretty_print(entrainment_coding_df[["Card7", "Card9"]].loc[["Round1", "Round2"]])

In [ ]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="dogs", pair_col="Pair_23"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex == 7) &
                           (transcript_df.Round.isin([1]))])

In [ ]:
# need to double check
pretty_print(entrainment_coding_df[["Card7"]].loc[["Round1"]])

### Baskets

In [75]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="baskets", pair_col="Pair_20"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex.isin([5])) &
                           (transcript_df.Round.isin([1,3]))])

In [ ]:
# need to double check 
pretty_print(entrainment_coding_df[["Card4"]].loc[["Round1", "Round3"]])

In [77]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="baskets", pair_col="Pair_20"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex.isin([10])) &
                           (transcript_df.Round.isin([1,2]))])

In [ ]:
# need to double check (striped)
pretty_print(entrainment_coding_df[["Card5"]].loc[["Round1", "Round2"]])

In [79]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="baskets", pair_col="Pair_21"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex.isin([9])) &
                           (transcript_df.Round.isin([1]))])

In [ ]:
# need to double check (one handle in middle)
pretty_print(entrainment_coding_df[["Card1"]].loc[["Round1"]])

In [81]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="baskets", pair_col="Pair_23"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex.isin([7])) &
                           (transcript_df.Round.isin([1,3]))])

In [ ]:
# need to double check (no gaps --> with the gaps? really big weave, biggest holes of all, the weaves?)
pretty_print(entrainment_coding_df[["Card3"]].loc[["Round1", "Round3"]])

In [83]:
transcript_df, entrainment_coding_df = get_pair_transcript_and_entrainment_coding_data(
    object_category="baskets", pair_col="Pair_43"
)
pretty_print(transcript_df[(transcript_df.TargetObjectIndex.isin([2])) &
                           (transcript_df.Round.isin([1]))])

In [ ]:
# looks correct
pretty_print(entrainment_coding_df[["Card9"]].loc[["Round1"]])